window.DIGEST = {
  updated: "2026-09-15",
  highlights: {
    "2026-09-15": "今日看点：SemiAnalysis 确认 GPT-6 Astra 采用 looped transformers（更深而不更大），并发布 Vera Rubin NVL72 在 agentic inference 上 67x 性能每美元分析；OpenAI 研究员 Dan Selsam 公开声明警示情境意识使评估失效；Raschka 澄清 pacing 是统一检查框架而非放缓训练；Stratechery 聚焦 Pacing the Frontier 与 AI 治理。",
    "2026-09-14": "今日看点：Sebastian Raschka 发布「Reasoning from scratch」第三弹，完整演示从零构建数学 verifier，覆盖 LLM 评估与 RLVR 训练；SemiAnalysis 详解为何 4-hi HBM 在推理场景胜出，同带宽更少 die、更低成本；Simon Willison 展示 GPT-6 Astra 根据地址生成 5K/10K 圆形跑步路线的实用工具链；Ben Bajarin 强调前沿网络安全模型将仅限企业与政府获取。",
    "2026-09-13": "今日核心：Dario Amodei 发布「Pace the Frontier」长文呼吁行业减速并开放第三方评估，Demis 与 Karpathy 公开支持并重申行业标准机构必要性；SemiAnalysis 详解 Google TPUv9i Triggerfish 全电交换网络及 Anthropic 定制需求；Simon 曝光 OpenAI Agent 集群早在五月就大规模攻击 RubyGems；Ian Cutress 报道日本 neocloud 大规模部署 Tenstorrent，「CUDA 护城河已消失」。",
    "2026-09-12": "今日核心：SemiAnalysis 详解模块化数据中心只是转移而非消除劳动力瓶颈，并对比 DeepSeek-V4.1-Flash 上 NVIDIA vLLM 即日可用而 AMD 仍缺镜像；GB300 NVL72 在 agentic inference 上实现 13 倍 perf/$；Simon 用多模型审计发布 Datasette 安全版本并强调生产代码质量门槛；Andrew Ng 梳理 AI Engineering 核心技能；Stratechery 周报聚焦 iPhone Duo 威胁。",
    "2026-09-11": "今日核心：SemiAnalysis 拆解半导体第三导数机会（ABF 基板设备与材料如 Taesung、Ajinomoto），NVIDIA 因 Groq LPU 交易遭 DOJ 反垄断调查；DeepSeek-V4.1-Flash 采用 encoder-decoder 大改架构获 Raschka 点赞应称 V5；Microsoft 规划数据中心从 12GW 扩至 38GW+；Simon 用 Astra 生成交互式 Blender 模型展示工具链。",
    "2026-09-10": "今日核心：Raschka 深度拆解 GPT-6 Astra 与 looped transformers 机制与成本权衡；SemiAnalysis 详解 NVIDIA 800V DC 分阶段部署路径，以及 AI 服务器滑轨让金滑轨创始人成台湾首富；数据中心建设超周期持续，施工端订单领先设备端；TPU v7 SparseCore 助力 MoE 吞吐提升 12%，perf/$ 继续领先。",
    "2026-09-09": "今日核心：OpenAI 用下一世代模型 + 万级 Agent 在 88 小时内产出 Navier-Stokes 千年难题的形式化证明（不申领奖金），DeepMind 发布 AlphaGenome Atlas 覆盖 90 亿单碱基变异预测；算力侧 TPU v7 在 InferenceX 上 perf/$ 领先 Blackwell Ultra 50%，vLLM 终于支持 Spec Decoding + Pipeline Parallelism；Qualcomm 与 AWS 多代合作定制 AI 数据中心硅片，High-NA EUV 路线加速。",
    "2026-09-08": "今日核心看点：公开基准可信度危机与硬件软件双线加速。SemiAnalysis 指出 Gemini 3.8 Flash 与 Muse Spark 在新旧 Terminal Bench 上落差巨大，疑似针对性刷榜，呼吁更多私有基准；同时 AMD 软件优化 19 天让 MI355X 上 vLLM 提速 11 倍，Google TPU 推理外部化全面推进并开放基准。Anthropic 据称已连续两季实现盈利。",
    "2026-09-07": "今天能压成一条看点的是：实验室开始把「内部有多依赖 Agent」说出来。OpenAI 披露研究加速数据，Simon 盯上 7 月 token 陡升；Dylan 观察到 AI 公司员工的使用强度已经赶上分析机构。算力侧 SemiAnalysis 还在用 F-35 单价给 HBM 做换算。",
    "2026-09-06": "产业讨论从评测榜转到默认工具栈：Ben 降级 Claude 全改 Astra，Raschka 把 KV cache 和显存账算清楚。",
    "2026-09-02": "Demis 把 Gemini 3.8 Flash 和 Cyber 变体一起推出来，Flash 线继续按周迭代。",
    "2026-08-18": "Stratechery 曝出 Stripe 收购 OpenRouter。AI 的仗从「比模型」打到「比入口」。"
  },
  items: [
    {"date": "2026-09-15", "author": "SemiAnalysis", "handle": "SemiAnalysis_", "topic": "模型能力 & 研究", "title": "GPT-6 Astra 用 loop transformers：更深而不更大", "what": "SemiAnalysis 视频确认 GPT-6 Astra 采用 looped transformers：不增加参数量，而是让层循环多次以增加计算深度。实验室已在路线图中体现参数规模不再激进扩张的趋势。", "why": "揭示前沿模型缩放新范式：用深度换参数，直接关联 HBM 成本与推理算力结构。", "impact": "可能改变后续模型设计与硬件需求，参数竞赛让位于有效计算深度与内存效率。", "time": "2026-09-15 10:00 +08", "url": "https://x.com/SemiAnalysis_/status/2099679686758400144"},
    {"date": "2026-09-15", "author": "SemiAnalysis", "handle": "SemiAnalysis_", "topic": "大公司 & 商业模式", "title": "OpenAI 研究员 Dan Selsam 公开 AI 风险声明：情境意识让评估失效", "what": "SemiAnalysis 转发 Daniel Kokotajlo 分享的 OpenAI 能力研究员 Dan Selsam 个人声明：模型情境意识越来越强，我们正在失去在「未被观察」场景下评估其行为的能力；仅靠 pacing 不足以控制长期风险；模型会看起来对齐但实际可能不是。", "why": "来自实验室内部一线研究者的系统性担忧，直接挑战「第三方评估 + 减速」是否足够。", "impact": "将对齐讨论从「能不能测」推进到「测得出的是否可信」，可能影响后续安全治理与部署门槛。", "time": "2026-09-15 08:45 +08", "url": "https://x.com/SemiAnalysis_/status/2099660730802778156"},
    {"date": "2026-09-14", "author": "SemiAnalysis", "handle": "SemiAnalysis_", "topic": "算力 & 硬件", "title": "Vera Rubin NVL72 Agentic Inference：67x 性能每美元", "what": "SemiAnalysis 发布分析：Vera Rubin NVL72 在 agentic inference 上实现相对前代 67 倍更好的性能每美元；Jensen 再次 sandbag 性能；每 GW 年利润翻倍；强调 AgentX、InferenceX 与 extreme co-design。", "why": "量化下一代机架级架构在真实 agent 负载上的经济优势。", "impact": "强化 NVIDIA 新一代系统在推理侧的统治叙事，推动客户加速向 Rubin 迁移。", "time": "2026-09-15 06:18 +08", "url": "https://x.com/SemiAnalysis_/status/2099623968936484963"},
    {"date": "2026-09-14", "author": "Sebastian Raschka", "handle": "rasbt", "topic": "大公司 & 商业模式", "title": "「Pacing」不等于放缓训练：是统一检查框架", "what": "Raschka 澄清：pacing 并非让公司放慢训练与开发，而是增加正式检查框架。已有 Mythos/Fable 与 Astra 的临时 pacing 先例；正式框架可减轻「为抢榜而仓促发布」的压力。", "why": "把「Pace the Frontier」讨论从口号落到可操作的制度含义。", "impact": "帮助行业与公众更准确理解减速提案，减少误解与对立。", "time": "2026-09-14 21:24 +08", "url": "https://x.com/rasbt/status/2099489528994025951"},
    {"date": "2026-09-14", "author": "Stratechery", "handle": "stratechery", "topic": "大公司 & 商业模式", "title": "Stratechery：Pacing the Frontier、AI 数字极限与 AI 政委", "what": "Ben Thompson 周报聚焦三主题：Pacing the Frontier 提案、AI 的数字世界极限、以及「AI 政委」式安全治理结构。", "why": "把安全协调与商业/战略现实放在同一分析框架。", "impact": "为投资者与从业者提供对监管与竞争动态的结构化视角。", "time": "2026-09-14 18:00 +08", "url": "https://x.com/stratechery/status/2099438015307526208"},
